### ISSUE TITLE
performance hit in `.order_samples`

### ISSUE THREAD

**Issue by josherrickson** [benbhansen-stats/propertee#132]
I was noticing that the example given by @kirkvanacore in #131 is quite a bit slower than I anticipated, so I ran the code through a profiler. Almost the entire time (~95%) is being spent in these lines of `.order_samples`: https://github.com/benbhansen-stats/flexida/blob/a77c68444da435f0a9216c98a459130fb623e693/R/DirectAdjusted.R#L295C50-L295C52

No action at the moment, just flagging as a potential place to examine speed-ups in the future.

A few ideas for speeding up:

- ~~Avoid duplication of `is.na` and `==`.~~
- Drop down to Rcpp for subsetting (as I think that's the biggest issue)
- Vectorize instead of loop? (`vapply(unique(Q_C_ix[!is.na(Q_C_ix)]), ...`?)

**Comment by nullsatz** [comment]
@josherrickson, do you still have the script that you profiled? If so, can you point me to it? Then, I can profile it too and possibly implement suggestions #2 and #3 in the original issue.

**Comment by josherrickson** [comment]
I don’t - I used the code in the opening comment with the synthetic data posted a bit further in the thread.
