### ISSUE TITLE
Variance estimation when `keys` slot of `SandwichLayer` has non-unique rows

### ISSUE THREAD

**Issue by jwasserman2** [benbhansen-stats/propertee#177]
Covariance model being fit using multiple observations from the same unit of assignment ID is causing an error in `vcov_tee`. This should be allowed, since units of assignment may be measured over multiple time periods. 

```r
> set.seed(23)
> cmod_data <- data.frame(yr = rep(c("00", "01", "02"), 5),
+                         id = rep(letters[1:5], each = 3),
+                         x = rnorm(5 * 3),
+                         y = rnorm(5 * 3))
> cmod <- lm(y ~ x, newdata_m)
> design_dat <- data.frame(id = letters[1:5], a = c(rep(1, 3), rep(0, 2)))
> des <- rct_design(a ~ unitid(id), newdesdat)
> analysis_dat <- data.frame(id = letters[1:5], yr = "02", x = rnorm(5),
+                            a = c(rep(1, 3), rep(0, 2)),
+                            y = rnorm(5))
> mod <- lmitt(y ~ 1, design = newdes, data = newanalysisdat, offset = cov_adj(cmod))
> vcov(mod)
Error in (function (x, cluster = NULL, type = NULL, cadjust = TRUE, multi0 = FALSE,  : 
  number of observations in 'cluster' and 'estfun()' do not match
```

The issue is that the `keys` slot of `SandwichLayer` does not have unique entries for each unit of assignment found in the covariance model fit.

```r
> mod$model$`(offset)`@keys
   id in_Q
1   a TRUE
2   a TRUE
3   a TRUE
4   b TRUE
5   b TRUE
6   b TRUE
7   c TRUE
8   c TRUE
9   c TRUE
10  d TRUE
11  d TRUE
12  d TRUE
13  e TRUE
14  e TRUE
15  e TRUE
```

The way that the ordering function `.order_samples()` aligns `estfun.teeMod()` and `.make_uoa_ids()` implicitly assumes this won't be the case at this line: https://github.com/benbhansen-stats/propertee/blob/840b84996427f12237fee81d50cce1bc99e8383c/R/teeMod.R#L375)

I don't think we want to change `keys`, because calculation of the `nc` constant depends on this being the number of rows used to fit the covariance adjustment model. I think we need to change `.make_uoa_ids()` here to grab `C_in_Q` rather than `Q_in_C`: https://github.com/benbhansen-stats/propertee/blob/840b84996427f12237fee81d50cce1bc99e8383c/R/teeMod.R#L297-L306

**Comment by benthestatistician** [comment]
I agree with the analysis of next steps given here (in particular, allowing the data frame in SL's `@keys` slot to have repeated rows).
