### ISSUE TITLE
.weights_calc problem w/ multiple blocking variables

### ISSUE THREAD

**Issue by benthestatistician** [benbhansen-stats/propertee#208]
I have an example in which `ate()` is giving me all 0s and NAs when it shouldn't.  Stepping through execution of `.weights_calc()` I see the following:

```r
e_z <- block_tx_units / block_units
##Browse[1]> e_z
##                grade_at_entry
## school_at_entry     1     2
##         112038 0.457 0.000
##         123056 0.415 0.222
to_reset_to_0 <- e_z == 1 | e_z == 0
## Brows<e[1]> to_reset_to_0
##                grade_at_entry
## school_at_entry     1     2
##          112038 FALSE  TRUE
##          123056 FALSE FALSE
```
Then comes the following, which doesn't seem right:
```r
to_reset_to_0 <- to_reset_to_0[as.character(blks[, 1])]
## Browse[1]> table(to_reset_to_0, exclude=NULL)
## to_reset_to_0
## <NA> 
## 164 
```
This would probably work if `to_reset_to_0` was a one-way table not a 2-way table and there was just one blocking variable.   But neither is true of my example, and we have:
```r
## Browse[1]> names(to_reset_to_0)
## NULL
## Browse[1]> head(blks, 3)
##   school_at_entry grade_at_entry
## 1          123056              2
## 2              NA             NA
## 3          112038              2
```
If a reprex is needed I attach materials for what should be one (not stopping to check that it gets all the way there): [i208reprex.zip](https://github.com/user-attachments/files/18141936/i208reprex.zip)

**Comment by josherrickson** [comment]
`as.character(blks[, 1])` obviously expected a single blocking variable, but I'm concerned there are more subtle assumptions elsewhere. What should it mean to have multiple blocks? Should `block(a, b)` and `block(paste(a, b))` produce the same results?

**Comment by benthestatistician** [comment]
Yes I think `block(a,b)` should be the same as `block(paste(a,b))`, or `block(interaction(a,b))`.  (In my example each school was separately randomly assigning kids, but in batches defined by the year of study entry.  So the block of interest can be thought of as `paste(school_at_entry, year_at_entry)`.

**Comment by josherrickson** [comment]
I've got a solution to this worked up, but requires touching some of Josh W's deep code.

https://github.com/benbhansen-stats/propertee/blob/55a515a80b924eb99a91bd19a35fb67cb9041827/R/teeMod.R#L269-L286

It looks like there's quite a bit of handling multiple block variables here, but `is.na(Q_obs[[var_names(x@StudySpecification, "b")]])]` fails. I replaced this with a check for NA's in any of the block variables:

```r
na_blocks <- apply(Q_obs[var_names(x@StudySpecification, "b")], 1, function(x) any(is.na(x)))
```

@jwasserman2 anything I may have missed here

**Comment by jwasserman2** [comment]
I think you can add `original_block = uoa_block_ids` to the `cbind()` call, then replace the existing `var_names()` call in the code with `original_block`. If that doesn't work, your code looks like it should be fine

**Comment by josherrickson** [comment]
@benthestatistician The weights in that example are no longer 0/NA. Let me know if they look OK.
