### ISSUE TITLE
`.new_StudySpecification()`'s `subset=` not finding variables in the data

### ISSUE THREAD

**Issue by benthestatistician** [benbhansen-stats/propertee#209]
I'm seeing
```r
rct_spec(z ~ uoa(uoa1,uoa2), subset= bid!=1, data=simdata)
##> Error: object 'bid' not found
simdata$bid_not_1 <- simdata$bid!=1
rct_spec(z ~ uoa(uoa1,uoa2), subset=bid_not_one, data=simdata)
##> Error: object 'bid_not_one' not found
```
but
```r
rct_spec(z ~ uoa(uoa1,uoa2), subset=simdata$bid_not_one, data=simdata)

 Randomized Control Trial

 Structure          Variables 
 ---------          --------- 
 Treatment          z         
 Unit of Assignment uoa1, uoa2
```

(Also to do: After this gets fixed, revisit /inst/examples/cov_adj.R on dataverse_star branch.)

**Comment by josherrickson** [comment]
I have an easy fix for this, but it breaks a bunch of tests in that frustrating way where interactive tests pass. I'll try and find time to look into this further. 

(Solution is adding `subset <- eval(substitute(subset), data, env)` inside each of the `*_spec` functions; errors are a mix of

**Comment by benthestatistician** [comment]
No insight here I'm afraid. (Which you may not be surprised by as this seems a type of question I could easily see myself bringing to you.) But good to hear you have an immediate handle on the problem.

**Comment by josherrickson** [comment]
Ok, this was an easy fix, just a scoping issue. Pushing a fix up momentarily.

**Comment by josherrickson** [comment]
Re-opening per your last comment in the opening statement; ready to close from my end.
