### ISSUE TITLE
in `lmitt.f(absorb=T)` , blocking var can be too short if there are NAs

### ISSUE THREAD

**Issue by benthestatistician** [benbhansen-stats/propertee#210]
Using `data(STARplus)` as introduced in the dataverse_star branch, I'm getting

```r
spec_ <- rct_spec(cond_at_entry ~ uoa(stdntid) + block(school_at_entry), data=STARplus, na.fail=F)
lmitt(g1readbsraw~1, data=STARplus, specification = spec_, dichotomy= cond_at_entry=="small" ~ .,   absorb=T)
Error in rowsum.default((wts * mm2)[grp_keep, ], grp[grp_keep], na.rm = TRUE) : 
  incorrect length for 'group'
```
The problem relates to NAs. In this example there's a bunch of rows of `STARplus` data that have NA for `school_at_entry`.  One of these rows also has an NA in `cond_at_entry`, but that variable is otherwise NA-free.  I think that when `lmitt.formula()` builds up its blocking variable, it's doing it in a way that kicks out that observation, but otherwise its reconstruction of the model matrix retains that observation.

**Comment by benthestatistician** [comment]
[dataverse-star 8a29588] commits a change to the vignette that's currently not building right in light of this issue.

**Comment by josherrickson** [comment]
Can you give a traceback? I'm curious at what point this is occuring.

For what it's worth, I'm not surprised we're running into more NA issues. We (or at least I) never handled those gracefully at the outset. Perhaps we need a serious rethink of how they're handled from the get-go.

**Comment by benthestatistician** [comment]
Here goes:
```r
> traceback()
7: stop("incorrect length for 'group'")
6: rowsum.default((wts * mm2)[grp_keep, ], grp[grp_keep], na.rm = TRUE)
5: rowsum((wts * mm2)[grp_keep, ], grp[grp_keep], na.rm = TRUE) at areg.center.R#18
4: sweep(rowsum((wts * mm2)[grp_keep, ], grp[grp_keep], na.rm = TRUE), 
       1, rowsum(wts[grp_keep], grp[grp_keep], na.rm = TRUE), FUN = "/") at areg.center.R#18
3: areg.center(mm, as.factor(blocks), lm.call$weights) at lmitt.R#302
2: lmitt.formula(g1readbsraw ~ 1, data = STARplus, specification = spec_, 
       dichotomy = cond_at_entry == "small" ~ ., absorb = T) at lmitt.R#86
1: lmitt(g1readbsraw ~ 1, data = STARplus, specification = spec_, 
       dichotomy = cond_at_entry == "small" ~ ., absorb = T)
```
Looking at the material being passed from `lmitt.formula()` down to `areg.center()` from within a debug session, I have
```r
Browse[1]> c(nobs_mm=nrow(mm), nobs_grp=length(grp))
 nobs_mm nobs_grp 
   13382    13381 
```
From a glance at the `lmitt.formula()` code, it seemed that this resulted from a model frame being built in slightly different ways at different point in the execution.  I wondered if when this gets done at [lmitt.R#L247-L257](https://github.com/benbhansen-stats/propertee/blob/70c6df70d3605dc0b88b10cb93c65312e95d0304/R/lmitt.R#L247-L257) for the purpose of constructing a blocking variable to absorb, it might be possible to instead use the data frame built previously at [lmitt.R#L108](https://github.com/benbhansen-stats/propertee/blob/70c6df70d3605dc0b88b10cb93c65312e95d0304/R/lmitt.R#L108).

**Comment by benthestatistician** [comment]
(I'm happy in general with our NA handling strategy, fwiw.  It's the sort of issue that's bound to present corner cases to work through.)

**Comment by josherrickson** [comment]
This is unrelated to blocks or `school_at_entry`:

```r
> data(STARplus)
> which(is.na(STARplus$stdntid))
[1] 13382
> SPsmall <- STARplus[13300:13382, c("cond_at_entry", "stdntid")]
> SPsmall$cond_at_entry[1:20] <- "small"
> spec <- rct_spec(cond_at_entry ~ uoa(stdntid), data = SPsmall, na.fail = FALSE)
> lmitt(g1readbsraw ~ 1, data = SPsmall, specification = spec,
+ dichotomy = cond_at_entry == "small" ~ ., absorb = T)
Error in rowsum.default((wts * mm2)[grp_keep, ], grp[grp_keep], na.rm = TRUE) : 
  incorrect length for 'group'
```

Continuing to debug.

**Comment by josherrickson** [comment]
I take it back - it is related to blocks via `absorb`:

```r
> data(STARplus)
> which(is.na(STARplus$stdntid))
[1] 13382
> SPsmall <- STARplus[13320:13382, c("cond_at_entry", "stdntid", "g1readbsraw")]
> SPsmall$cond_at_entry[1:20] <- "small"
> spec <- rct_spec(cond_at_entry ~ uoa(stdntid), data = SPsmall, na.fail = FALSE)
> lmitt(g1readbsraw ~ 1, data = SPsmall, specification = spec,
+ dichotomy = cond_at_entry == "small" ~ ., absorb = TRUE)
Error in rowsum.default((wts * mm2)[grp_keep, ], grp[grp_keep], na.rm = TRUE) : 
  incorrect length for 'group'
> lmitt(g1readbsraw ~ 1, data = SPsmall, specification = spec,
+ dichotomy = cond_at_entry == "small" ~ ., absorb = FALSE)
cond_at_entry. 
       2.77381 
```

**Comment by josherrickson** [comment]
(I'm leaving running commentary because my free time today is very scattered and I'll be working on this in intermittent blocks - if this is urgent and anyone sees a solution before I get to, feel free to jump in.)

**Comment by josherrickson** [comment]
The issue is exactly where you said - the call to `blocks` at line 252 drops NA. I think this is as simple as adding `na.action = na.fail` to https://github.com/benbhansen-stats/propertee/blob/70c6df70d3605dc0b88b10cb93c65312e95d0304/R/StudySpecificationAccessors.R#L653

It appears to work; can you test it on your end? If everything looks good, it might make sense to add an argument to `blocks` (and other accessors) of `na.action = na.pass`? Or at least to `.get_col_from_new_data` for internal use.

(PS rather than loading AER directly in tests, `if (requireNamespace("AER", quietly = TRUE)) {` should avoid tripping CRAN checks.)

**Comment by josherrickson** [comment]
PS I'm happy to make these fixes in main, just wanted to give you a chance to weigh in on your end before moving that forward.

**Comment by benthestatistician** [comment]
This all sounds right to me, but I may not be the best person to comment on the idea of adding another arg to `blocks()` and/or `.get_col_from_new_data()`.  @jwasserman2, would you be willing to look over [this proposal](https://github.com/benbhansen-stats/propertee/issues/210#issuecomment-2551765562) on this thread and tell us what you think? (Josh E, 2672740 takes the `requireNamespace("AER")` suggestion; thanks for that.)

**Comment by jwasserman2** [comment]
I think the addition of `na.action = na.pass` is the right call there. It looks like it'll match the dimension of `mm` when called later on in `lmitt.formula()`, given that `na.action=na.pass` is part of the call for creating `mm`.

**Comment by josherrickson** [comment]
Ok, I made this fix. I actually decided against adding an argument to toggle this handling of NA's - right now the only NA option we have in `_spec` is `na.fail`. If we eventually want to expand that to `na.action`, perhaps we can pass it down to `.get_col_from_new_data`, but for right now it doesn't quite make sense.
