### ISSUE TITLE
`absorb=TRUE` should residualize rather than fit fixed effects

### ISSUE THREAD

**Issue by josherrickson** [benbhansen-stats/propertee#77]
https://github.com/benbhansen-stats/flexida/issues/59#issuecomment-1262475339

This functionality should be used for `absorb=TRUE` instead of the current version.

**Comment by benthestatistician** [comment]
As noted earlier in this thread, we decided in spring 2023 that `lmitt.f(..., absorb=T)` should do
`y ~ aregcenter(x)`, returning an `(Intercept)` coefficient as well as main and moderator effects.  Previously it had been  `aregcenter(y) ~ aregcenter(x) + 0`. 

The considerations that led us to drop `y`-centering are indicated at various points in this comment thread, but I'm having a hard time reconstructing the rationale for doing `y ~ aregcenter(x)` as opposed to  `y ~ aregcenter(x) +0`  (which would leave off the intercept).  @josherrickson can you help? (The standard error story would be cleaner with the intercepts excluded from fitting.  But this isn't necessarily decisive, particularly if there are other reasons to include it.)

**Comment by josherrickson** [comment]
`y ~ areg(x)` versus `y ~ areg(x) + 0` will yield different coefficients on `areg(x)`, when areg is `z - groupmean(z) + grandmean(z)`:

```r
> data(mtcars)
> mtcars$gear <- as.factor(mtcars$gear)
> getdrat <- function(mod) {
+     mod$coeff[which(grepl("drat", names(mod$coef)))]
+ }
> getdrat(lm(mpg ~ drat + as.factor(gear), data = mtcars))
    drat 
5.294113 
```

```r
> areg <- function(var, grp) {
+     var - tapply(var, grp, mean, na.rm = FALSE)[grp] + mean(var, na.rm = TRUE)
+ }
```

```r

> getdrat(lm(areg(mpg, gear) ~ areg(drat, gear), data = mtcars))
areg(drat, gear) 
        5.294113 
> getdrat(lm(mpg ~ areg(drat, gear), data = mtcars))
areg(drat, gear) 
        5.294113 
> getdrat(lm(mpg ~ areg(drat, gear) + 0, data = mtcars))
areg(drat, gear) 
        5.584151 
```
Removing the re-addition of grand mean does allow those models to return the same coefficients.
```r
> areg2 <- function(var, grp) {
+     var - tapply(var, grp, mean, na.rm = FALSE)[grp]
+ }
```
```r
> getdrat(lm(areg2(mpg, gear) ~ areg2(drat, gear), data = mtcars))
areg2(drat, gear) 
         5.294113 
> getdrat(lm(mpg ~ areg2(drat, gear), data = mtcars))
areg2(drat, gear) 
         5.294113 
> getdrat(lm(mpg ~ areg2(drat, gear) + 0, data = mtcars))
areg2(drat, gear) 
         5.294113 
```

Stata's `areg` includes the re-addition of the grand mean.

**Comment by josherrickson** [comment]
At this point, not really. We've already diverged a lot from what both `lm` and Stata are doing.

**Comment by benthestatistician** [comment]
Thanks! This is a quite helpful reconstruction of considerations leading us to where we landed. 

I now lean toward leaving it as-is (intercept included), if for different reasons that informed our path previously.  Excluding the intercept makes the standard errors story a bit cleaner but would likely increase our calculated SEs' departure from SEs that other packages would offer -- in the direction of making them bigger, I think.
